### PR TITLE
Issue/#39/eviction warning scrooge core

### PR DESCRIPTION
**Pull request by RayRoestenburg**
See #39

### CODE REVIEW

**Comment by SamRoberts** [comment]
@RayRoestenburg you might want to check out this and other changes in the CDH5_new_deps branch (https://github.com/CommBank/uniform/tree/CDH5_new_deps), which I hope to merge into master soon.

**Comment by SamRoberts** [comment]
Oh, and :+1:

**Comment by RayRoestenburg** [comment]
Cool thanks, didn't notice the branch, looks like a really nice cleanup! (this is just a quick fix for an annoying warning I wanted to get out of the way ;-)

**Comment by RayRoestenburg** [comment]
I don't understand why it fails on 'push' and not on 'pr' though, is that normal? (not too familiar with the setup), looking forward to the full cleanup in https://github.com/CommBank/uniform/tree/CDH5_new_deps which also includes this change. Close this and wait for new deps, or merge?

**Comment by SamRoberts** [comment]
I'm entirely happy for you to merge this now. Dealing with the conflict will add approximately 5 seconds to my workload when I go to merge my changes with master, which is completely insignificant in the grand scheme of things. :smile: 

Re: the failure, my initial guess is that the # in your branch name is confusing the script, as the majority of the "unique" part of the url name is now a fragment identifier. Maybe try changing the branch name to something without any special symbols and redoing the PR? Just a guess ...

**Comment by RayRoestenburg** [comment]
Closing this pull request to test Sam's guess about the # in the branch name

**Pull request closed without merging**
