### PR TITLE
Bump scalding version to 0.16.0

### PR DESCRIPTION
**Pull request by toddmowen**
No particular reason, but it has been more than a year since the scalding version was last updated.

### CODE REVIEW

**Comment by vineethvarghese** [comment]
Have you tested any jobs on 0.16.0?

**Comment by toddmowen** [comment]
@vineethvarghese No I haven't. Do you mean using dependencyOverrides for just scalding & algebird?

My original plan was to roll it out to all the commbank components one-by-one (using wrangler), deal with any breakages along the way, and not test a job until maestro/coppersmith have been rebuilt (if at all).

**Comment by vineethvarghese** [comment]
:) I am happy if you are taking this up. It was on @rowandavies pipeline anyway.

**Comment by rowandavies** [comment]
@toddmowen So far I've successfully run all the maestro tests locally with scalding 0.16 via a branch of uniform.  My next step was going to be to test the stash project etl.test-jobs on the cluster, but I can't do that until I get back now (in 4 weeks).  If that works, we have some confidence, and it could be reasonable to roll out 0.16.  Of course, we do need to be prepared to deal with any tweaks required in our libraries if issues come up in jobs.  

(This reminds me that I was going to propose a Scala Omnia Libraries guild to coordinate activities around our libraries.)

**Comment by vineethvarghese** [comment]
@toddmowen Are you happy to push this across the stack i.e. etl-plugins and update the version on etl.tests.job? This will be a quick way to run a test on the cluster and it is all version update across the stack.

**Comment by toddmowen** [comment]
@rowandavies Obviously I didn't realise you had already started working on this. Did you rebuild all the (commbank) dependencies of maestro as well? Did you run into any issues with 0.16 along the way?

I have nothing waiting on this change, and so I don't mind leaving it until you get back. Or I can take it up now.

**Comment by toddmowen** [comment]
@rowandavies I'm ready to pick this up again. I have [scripts ready](https://github.com/CommBank/autowrangler) to automate a fair amount of the drudge work (for github repos at least). Based on your previous investigations, do you know of any problems that I'm likely to run into with the new scalding version?

If not, then I will optimistically assume that it is backwards compatible and no code changes to our libraries will be required...

**Comment by rowandavies** [comment]
Apologies, I never got to this.  No, I didn't find any issues, but I didn't get that far beyond the maestro tests.  It should be backward compatible and we can always have uniform go to the previous version if we have to.

I think I like autowrangler, but I'm not sure I have time to understand the detail fully.  Perhaps we should meet briefly?

**Pull request merged**
