### PR TITLE
Update Scala 2.10 and 2.11 versions to latest

### PR DESCRIPTION
**Pull request by mjhopkins**
This PR udpates to the latest 2.10 and 2.11 patch releases.

Release notes:
http://www.scala-lang.org/news/2.10.6
http://www.scala-lang.org/news/2.11.7

### CODE REVIEW

**Comment by stephanh** [comment]
Can you bump the version in `version.sbt` as well.

Thank you @mjhopkins :+1:

**Comment by mjhopkins** [comment]
@stephanh sure
Is that 1.4.1 -> 1.5.0, or 1.4.1 -> 1.4.2?

**Comment by stephanh** [comment]
What do you feel like? :smile:. Maybe a minor version bump since there is enough cutting edge projects going on in Omnia that someone might really care about the particular scala version.

**Comment by mjhopkins** [comment]
@stephanh that sounds reasonable.

Also, `macro-paradise` has a separate release for every Scala patch release.
We may need someone with the requisite permissions to copy artefacts across to the internal artifactory.
i.e.
`"org.scalamacros" % "paradise_2.10.6" % "2.1.0"`
and
`"org.scalamacros" % "paradise_2.11.7" % "2.1.0"`

"org.scalamacros" % "quasiquotes" for Scala 2.10 was similarly versioned by Scala patch version. Is anyone still using this?

**Comment by stephanh** [comment]
We aren't using macros in Scala 2.10 anymore.

How do you feel about adding `paradise` to Uniform dependencies project? Thereby if we change the scala version number we only have to fix it up in 1 place?

**Comment by mjhopkins** [comment]
Done.

**Pull request closed without merging**
